import React from 'react';
import { Inter } from 'next/font/google';
import '@/app/globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Miaouflix',
  description: 'Generated by create next app',
  robots: 'noindex, nofollow',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className={inter.variable}>
      <body className="min-h-full bg-neutral-900 text-neutral-50">
        <main>{children}</main>
      </body>
    </html>
  );
}
